project:
  type: website
  output-dir: docs

website:
  title: "Furkan Zerman"
  favicon: logo.jpeg
  open-graph: true
  twitter-card: true
  site-url: fzerman.github.io
  navbar:
    left:
      - projects.qmd
      - links.qmd
      - posts.qmd
    right:
      - icon: github
        href: https://github.com/fzerman
      - icon: linkedin
        href: https://www.linkedin.com/in/furkan-zerman-6592851b4
format:
  html:
    theme: darkly
    css: styles.css



